print ("################################")
print ("#                              #")
print ("#  Muhammad Kholid Syaifullah  #")
print ("#         2210817210025        #")
print ("#                              #")
print ("################################")
